CcxwsExchangeConnectorSwisschain:

    Main:

        Exchanges:
            settings-key: CcxwsExchangeConnector-Swisschain-Exchanges
            types:
              - JsonArray

        Symbols:
            settings-key: CcxwsExchangeConnector-Swisschain-Symbols
            types:
              - JsonArray

        AssetsMapping:
            settings-key: CcxwsExchangeConnector-Swisschain-AssetsMapping
            types:
              - JsonArray

        ExchangesNamesSuffix:
            settings-key: CcxwsExchangeConnector-Swisschain-ExchangesNamesSuffix

        ReconnectIntervalMs:
            settings-key: CcxwsExchangeConnector-Swisschain-ReconnectIntervalMs

        LoggingLevel:
            settings-key: CcxwsExchangeConnector-Swisschain-LoggingLevel

        Events:

            Quotes:
                Subscribe:
                    settings-key: CcxwsExchangeConnector-Swisschain-Events-Quotes-Subscribe
                Publish:
                    settings-key: CcxwsExchangeConnector-Swisschain-Events-Quotes-Publish

            OrderBooks:
                Subscribe:
                    settings-key: CcxwsExchangeConnector-Swisschain-Events-OrderBooks-Subscribe
                Publish:
                    settings-key: CcxwsExchangeConnector-Swisschain-Events-OrderBooks-Publish
                PublishingIntervalMs:
                    settings-key: CcxwsExchangeConnector-Swisschain-Events-OrderBooks-PublishingIntervalMs

            Trades:
                Subscribe:
                    settings-key: CcxwsExchangeConnector-Swisschain-Events-Trades-Subscribe
                Publish:
                    settings-key: CcxwsExchangeConnector-Swisschain-Events-Trades-Publish

    RabbitMq:
        Disabled:
            settings-key: CcxwsExchangeConnector-Swisschain-RabbitMq-Disabled
        ConnectionString:
            settings-key: RawPriceRabbitMq
            types:
              - AzureTableStorage
        Quotes:
            settings-key: CcxwsExchangeConnector-Swisschain-RabbitMq-Quotes
        OrderBooks:
            settings-key: CcxwsExchangeConnector-Swisschain-RabbitMq-OrderBooks
        Trades:
            settings-key: CcxwsExchangeConnector-Swisschain-RabbitMq-Trades

    SocketIO:
        Disabled:
            settings-key: CcxwsExchangeConnector-Swisschain-SocketIO-Disabled
        Port:
            settings-key: CcxwsExchangeConnector-Swisschain-SocketIO-Port

SlackNotifications:
    AzureQueue:
        ConnectionString:
            settings-key: SlackNotificationsConnString
            types:
                - AzureTableStorage
        QueueName:
            settings-key: SlackQueueName

MonitoringServiceClient:
    MonitoringServiceUrl:
        settings-key: MonitoringServiceUrl

