CcxwsExchangeConnector:

    Main:

        Exchanges:
            settings-key: CcxwsExchangeConnector-Exchanges
            types:
              - JsonArray

        Symbols:
            settings-key: CcxwsExchangeConnector-Symbols
            types:
              - JsonArray            

        AssetsMapping:
            settings-key: CcxwsExchangeConnector-AssetsMapping
            types:
              - JsonArray  

        ExchangesNamesSuffix:
            settings-key: CcxwsExchangeConnector-ExchangesNamesSuffix

        ReconnectIntervalMs:
            settings-key: CcxwsExchangeConnector-ReconnectIntervalMs

        LoggingLevel:
            settings-key: CcxwsExchangeConnector-LoggingLevel

        Events:

            Quotes:
                Subscribe:
                    settings-key: CcxwsExchangeConnector-Events-Quotes-Subscribe
                Publish:
                    settings-key: CcxwsExchangeConnector-Events-Quotes-Publish

            OrderBooks:
                Subscribe:
                    settings-key: CcxwsExchangeConnector-Events-OrderBooks-Subscribe
                Publish:
                    settings-key: CcxwsExchangeConnector-Events-OrderBooks-Publish
                PublishingIntervalMs:
                    settings-key: CcxwsExchangeConnector-Events-OrderBooks-PublishingIntervalMs

            Trades:
                Subscribe:
                    settings-key: CcxwsExchangeConnector-Events-Trades-Subscribe
                Publish:
                    settings-key: CcxwsExchangeConnector-Events-Trades-Publish

    RabbitMq:
        ConnectionString:
            settings-key: RawPriceRabbitMq
            types:
              - AzureTableStorage
        OrderBooks:
            settings-key: CryptoIndexService-OrderBooks
        TickPrices:
            settings-key: CryptoIndexService-TickPrices


SlackNotifications:
    AzureQueue:
        ConnectionString:
            settings-key: SlackNotificationsConnString
            types:
                - AzureTableStorage
        QueueName:
            settings-key: SlackQueueName

MonitoringServiceClient:
    MonitoringServiceUrl:
        settings-key: MonitoringServiceUrl

