name: Release Service

on:
  push:
    tags: "service-*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: npm install
    - name: Publish to Registry
      uses: swisschain/Publish-Docker-Github-Action@master
      with:
        name: swisschains/ccxws-exchange-adapter
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: ./
        tag_names: true
	tag_name_skip: service-